// CommmonJS, every file is module (by default)
// Modules - Encapsulated code (only share minimun)
const names = require('./4-name')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavor')
require('./7-mine-grenade')
console.log(data)
sayHi('Susan')
sayHi(names.john)
sayHi(names.peter)